void version(void);
void op_add(char *, char *);
void op_sub(char *, char *);
void op_div(char *, char *);
void op_mul(char *, char *);
void op_fibo(char *);
void op_addv(char *, char *);
void op_subv(char *, char *);
void op_mulv(char *, char *);
void op_load(char *);
void op_search(char *);
